SET SERVEROUTPUT ON
SET FEEDBACK 1
SET ECHO OFF

BEGIN
	DBMS_OUTPUT.PUT_LINE('TCODE NAME       BALANCE   ');
	DBMS_OUTPUT.PUT_LINE('----- ---------- ----------');
	FOR CREC IN (SELECT * FROM TCUST) LOOP
		DBMS_OUTPUT.PUT_LINE(CREC.C_CODE || ' ' || RPAD(CREC.LNAME,10) || ' ' || LPAD(CREC.BALANCE,10,' '));
	END LOOP;
	DBMS_OUTPUT

	DBMS_OUTPUT.PUT_LINE('----- ---------- ----------');
END;
/


/*
DECLARE
	MYQUOTE VARCHAR2(80) := 'TO BEGIN, BEGIN...';
BEGIN
	DBMS_OUTPUT.PUT_LINE('ME:= '||MYQUOTE);
END;
/


CREATE TABLE TCUST
	AS SELECT C_CODE, LNAME, BALANCE
		FROM CUSTOMER;


DECLARE
	BKNT CONSTANT INT := 10009;
	KNT INT;
	MXKNT INT;
	--/*
	--TCODE TCUST.C_CODE%TYPE;
	--NAME TCUST.LNAME%TYPE;
	--BAL TCUST.BALANCE%TYPE;
	CREC TCUST%ROWTYPE;

BEGIN
	SELECT COUNT(*) INTO MXKNT
		FROM TCUST;
	DBMS_OUTPUT.PUT_LINE('TCODE NAME       BALANCE   ');
	DBMS_OUTPUT.PUT_LINE('----- ---------- ----------');
	FOR KNT IN 1 .. MXKNT LOOP
		SELECT * INTO CREC
			FROM TCUST 
			WHERE C_CODE = (BKNT + KNT);
		DBMS_OUTPUT.PUT_LINE(CREC.C_CODE || ' ' || RPAD(CREC.LNAME,10) || ' ' || LPAD(CREC.BALANCE,10,' '));
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('----- ---------- ----------');
	DBMS_OUTPUT.PUT_LINE(MXKNT || ' ROWS SELECTED...');
END;
/

*/