SET ECHO ON
SET FEEDBACK ON

REM THIS is CREATION OF A TABLE

--SPOOL "E:\Practicals\VI Sem\DBMS\prac1.txt" APPEND

INSERT INTO EMPLOYEE(EID, FNAME, LNAME, BIRTHDATE, GENDER, HIREDATE, SALARY, DEPARTMENT, DESIGNATION, SSN) VALUES
	(7110, 'Svetlana', 'Sanders', '15-OCT-1984', 'M', '15-JAN-2006', 10000, 'Machine Vision', 'Lecturer', '44MA123456');

COMMIT;

SET FEEDBACK OFF
SET ECHO OFF

--SPOOL OFF